[versions]
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "28"
android-targetSdk = "36"
androidx-activityCompose = "1.13.0"
androidx-appcompat = "1.7.1"
androidx-constraintlayout = "2.2.1"
androidx-core-ktx = "1.18.0"
androidx-espresso-core = "3.6.1"
androidx-material = "1.13.0"
androidx-test-junit = "1.2.1"
compose-plugin = "1.10.3"
junit = "4.13.2"
kotlin = "2.3.20"

ktor = "3.4.2"
kamel = "1.0.9"
kotlinx-coroutines = "1.10.2"
koin = "4.2.1"
koinComposeMultiplatform = "4.2.1"
libraryVersion = "4.3.1"
navigationCompose = "2.9.2"
lifecycleViewModel = "2.10.0"
androidx-data-store = "1.2.1"
androidx-startup = "1.2.0"
room = "2.8.4"
ksp = "2.3.6"
sqlite = "2.6.2"
dateTime = "0.7.1-0.6.x-compat"
accompanistPermissionsVersion = "0.37.3"
firebase-android-bom = "34.12.0"
gradlePlugins-crashlytics = "3.0.7"
gradlePlugins-google-services = "4.4.4"
work_version = "2.11.2"
shimmer_version = "1.3.3"
kermit_version = "2.1.0"
gradle-buildconfig-plugin = "6.0.9"
haze_version = "1.7.2"
animationCoreAndroidVersion = "1.10.6"
lottie_version = "2.1.0"
git_live_version = "2.4.0"
material_icons = "1.7.3"
composeWebviewMultiplatformVersion = "2.0.3"
material3 = "1.10.0-alpha05"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kamel = { module = "media.kamel:kamel-image-default", version.ref = "kamel" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-plugin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-plugin" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-plugin" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-plugin" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-plugin" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewModel" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

library = { module = "com.github.chuckerteam.chucker:library", version.ref = "libraryVersion" }
library-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "libraryVersion" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewModel" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeMultiplatform" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinComposeMultiplatform" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-data-store-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-data-store" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-runtime-android = { module = "androidx.room:room-runtime-android", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTime" }
lottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "lottie_version" }
gitlive_analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "git_live_version" }
gitlive_auth = { module = "dev.gitlive:firebase-auth", version.ref = "git_live_version" }
gitlive_storage = { module = "dev.gitlive:firebase-storage", version.ref = "git_live_version" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material_icons" }
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebviewMultiplatformVersion" }


android-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissionsVersion" }
firebase-android-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-android-bom" }
firebase-android-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics" }
firebase-android-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-android-inappmessaging = { module = "com.google.firebase:firebase-inappmessaging-display" }
firebase-android-firestore = { module = "com.google.firebase:firebase-firestore" }
androidx-workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "work_version" }
kmp-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimmer_version" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit_version" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze_version" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze_version" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "gradlePlugins-crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "gradlePlugins-google-services" }
gradleBuildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gradle-buildconfig-plugin" }

[bundles]
ktor = [
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-client-auth",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json",
]